Niko/aws config
merivercap/100x-Backend pull request #2
Opened 2018-06-28 23:50 UTC by niko79542

Just added some settings for elastic beanstalk

2018-06-30 20:21 UTC, jay-ithiel commented on package.json
> +    "start": "node ./src/server/server.js",
Tried running `npm start` and it threw:

100x-backend@1.0.0 start /Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend
node ./src/server/server.js

module.js:544
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/src/server/server.js:1:63)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)

2018-06-30 20:27 UTC, jay-ithiel commented on src/config/config.js
>    },
the `rds.js` file we are pulling from isn't complete yet. Just made a todo commit in `rds.js`

2018-06-30 20:30 UTC, jay-ithiel requested changes
- npm start script can't find dotenv in server.js
- rds.js config isn't complete yet

2018-07-01 16:08 UTC, niko79542 commented
Sounds good.  dotenv was the npm package I was using to set environment variables.  Wasn't sure if theres a better way.  G2g for a bit.  Ill be back at 11:30

2018-08-05 01:04 UTC, closed without merging